trigger: none
jobs:

- job: BuildApp
  pool:
    vmImage: 'windows-latest'

  variables:
    buildConfiguration: 'Debug'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

  steps:

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'
        pwd
        ls -R

  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: 'SQLiteAppTools.Build.sln'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/SQLiteAppTools/SQLiteAppTools.csproj'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/SQLiteAppTools.Tests/SQLiteAppTools.Tests.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/SQLiteAppTools.Tests/SQLiteAppTools.Tests.csproj'
